package command;

public enum CommandType {
    CREATE_DOCTOR,
    CREATE_PATIENT,
    CREATE_APPOINTMENT,
    DELETE_PATIENT,
    DELETE_DOCTOR,
    DELETE_APPOINTMENT,
    VIEW_DOCTOR,
    VIEW_APPOINTMENT,
    UPDATE_PATIENT,
    UPDATE_APPOINTMENT,
    VIEW_PATIENT,
    HELP,
    EXIT,
    UNDEFINED
}
